<?xml version="1.0"?>
<!DOCTYPE main [
  <!ELEMENT main (a|b)*>
  <!ELEMENT a (#PCDATA)>
  <!ATTLIST a id ID #REQUIRED>
  <!ELEMENT b (#PCDATA)>
]>
<main>
  <a id="w">W</a>
  <a id="x">X</a>
  <a id="y">Y</a>
  <a id="z">Z</a>
  <b>y</b>
  <b>w</b>
  <b>x</b>
</main>