=== chardmeier/docent/external/arabica/tests/XSLT/testsuite/DOCS/Background/disc.dtd
<!--Configurable Test Suite Discretionary items-->
<!--$Id: disc.dtd,v 1.6 2001/12/07 15:56:29 Administrator Exp $-->
<!--
  Catalogue of discretionary items in a specification.
  This catalog may be used to generate:
    1. A narrative document about discretionary items
    2. A questionnaire for developers about choices they made
    3. Validation data for an associated test-case catalog
-->
<!--
Copyright (C) The Organization for the Advancement of
Structured Information Standards [OASIS] (2001). All Rights Reserved.

This document and translations of it may be copied and furnished to
others, and derivative works that comment on or otherwise explain it or
assist in its implementation may be prepared, copied, published and
distributed, in whole or in part, without restriction of any kind,
provided that the above copyright notice and this paragraph are included
on all such copies and derivative works. However, this document itself
may not be modified in any way, such as by removing the copyright notice
or references to OASIS, except as needed for the purpose of developing
OASIS specifications, in which case the procedures for copyrights
defined in the OASIS Intellectual Property Rights document must be
followed, or as required to translate it into languages
other than English.

The limited permissions granted above are perpetual and
will not be revoked by OASIS or its successors or assigns.

This document and the information contained herein is provided on an
"AS IS" basis and OASIS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO ANY WARRANTY THAT THE USE OF THE INFORMATION
HEREIN WILL NOT INFRINGE ANY RIGHTS OR ANY IMPLIED WARRANTIES OF
MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
-->

<!--common fragments-->

<!ENTITY % prose "#PCDATA | em | strong | span">
<!ENTITY % citations SYSTEM "citation.dtd">
%citations;

<!--========================================================================-->
<!--high-level constructs-->
<!ELEMENT doc (verbiage, items, interlocks, changes)>
<!ATTLIST doc date CDATA #REQUIRED
          configuration-href CDATA #REQUIRED>
<!ELEMENT items ( item )*>
<!ELEMENT interlocks ( interlock* )>
<!ELEMENT changes ( change* )>

<!-- verbiage is used in the narrative document
     items contains all <item> elements, regardless of attributes
     interlocks is the means of associating items that are interdependent
     changes is for internal logging and the long-form human-readable document -->

<!--========================================================================-->
<!--mid-level constructs-->

<!ELEMENT title ( %prose; )*>
<!ELEMENT intro ( p | ul )*>
<!ELEMENT verbiage ( title, intro, group-intro*, question-intro )>
<!ELEMENT group-intro ( p | ul )*>
<!ATTLIST group-intro status ID #REQUIRED>
<!ELEMENT question-intro ( p | ul )*>
<!ELEMENT item ( spec-citation+, choices?, excerpt, question*, elaborator? )>
<!ATTLIST item id ID #REQUIRED
               expandable CDATA #IMPLIED
               status IDREF #REQUIRED>
<!ELEMENT choices ( choice+ )>
<!ATTLIST choices mootable (yes | no) #IMPLIED>
<!ELEMENT excerpt ( p | ul )*>

<!ELEMENT interlock ( p | ul )*>
<!ELEMENT change ( p | ul )*>

<!--========================================================================-->
<!--low-level constructs-->

<!ELEMENT p ( %prose; | party | all-choices )*>
<!ATTLIST p style CDATA #IMPLIED>
<!ELEMENT strong ( %prose; )*>
<!ELEMENT em ( %prose; )*>
<!ELEMENT span ( %prose; )*>
<!ATTLIST span style CDATA #REQUIRED>
<!ELEMENT ul ( li* )>
<!ELEMENT li ( %prose; | party )*>
<!ELEMENT question ( %prose; )*>
<!ATTLIST question scope ( Filter | Configuration | Prototype ) #IMPLIED>
<!-- A question of the "Filter" type should be expressed so that test cases can be
     included/excluded based on the answers; it would typically be used if the
     "status" of the item is not Configuration or Recognized.
     For Configuration, question should elicit information useful to the Test Lab.
     A Prototype question is a general example, which will be instantiated as a
     Filter question for each language/locale represented in the test suite.
     "Recognized" items probably don't warrant a question, hence it's optional. -->
<!ELEMENT choice EMPTY>
<!ATTLIST choice value CDATA #REQUIRED>
<!-- Don't validate values here, because the function of a document conforming to
     this DTD is to *define* the values. Note, however that the use of "yes" and "no"
     is discouraged for Filter questions (for readability). -->
<!ELEMENT elaborator ( %prose; )*>
<!ATTLIST elaborator choice CDATA #REQUIRED>
<!ATTLIST change date CDATA #REQUIRED>

<!--========================================================================-->
<!--specialist low-level constructs-->

<!ELEMENT party EMPTY>
<!ATTLIST party idref IDREF #REQUIRED>
<!ELEMENT all-choices EMPTY>

<!--end of file-->

=== chardmeier/docent/external/arabica/tests/XSLT/testsuite/DOCS/Background/xsltdisc.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE doc SYSTEM "../support/disc.dtd">
<!--
Copyright (C) The Organization for the Advancement of
Structured Information Standards [OASIS] (2001). All Rights
Reserved.

This document and translations of it may be copied and
furnished to others, and derivative works that comment on
or otherwise explain it or assist in its implementation may
be prepared, copied, published and distributed, in whole
or in part, without restriction of any kind, provided that the
above copyright notice and this paragraph are included on
all such copies and derivative works. However, this
document itself may not be modified in any way, such as by
removing the copyright notice or references to OASIS,
except as needed for the purpose of developing OASIS
specifications, in which case the procedures for copyrights
defined in the OASIS Intellectual Property Rights document
must be followed, or as required to translate it into
languages other than English.

The limited permissions granted above are perpetual and
will not be revoked by OASIS or its successors or assigns.

This document and the information contained herein is
provided on an "AS IS" basis and OASIS DISCLAIMS ALL
WARRANTIES, EXPRESS OR IMPLIED, INCLUDING
BUT NOT LIMITED TO ANY WARRANTY THAT THE USE
OF THE INFORMATION HEREIN WILL NOT INFRINGE
ANY RIGHTS OR ANY IMPLIED WARRANTIES OF
MERCHANTABILITY OR FITNESS FOR A PARTICULAR
PURPOSE.
-->
<doc date="$Date: 2001/12/07 20:51:34 $(UTC)" configuration-href="xsltcfg.xml">
  <verbiage>
  <title>Discretionary behavior in '<strong>XSL
Transformations (XSLT)</strong>' and '<strong>XPath</strong>'</title>
   <intro>
         <p>This document details identified areas of the XSLT and XPath
Recommendations that describe or allow optionality in the behavior
of an XSLT processor. The majority of the identified optional or
discretionary behavior concerns detection or recovery from error
conditions, but other areas have been identified as well. This
document is also the foundation for a questionnaire for developers
of XSLT processors; it asks questions that a test lab would need
answered in order to administer the test suite to that devloper's
processor.</p>
         <p>Each area of discretionary behavior is shown as an entry
comprising at least five items:</p>
         <ul>

            <li>Unique, descriptive, but somewhat arbitrary identifier (used in
cataloging test cases)</li>


            <li>A simple citation of the XSLT Recommendation section number and
title of the section containing the description of the discretionary behavior, or
erratum number</li>


            <li>A more complex citation in the form of an XPath for locating the
excerpt of the XML version of the XSLT or XPath Recommendation or
Errata document</li>


            <li>Excerpt from the XSLT or XPath Recommendation of the paragraph
or other element located by the XPath and containing the
description of the discretionary error handling. The description of
the discretionary behavior is highlighted.</li>


            <li>Description of the discretionary behavior recast as a question,
which can be answered briefly. The questions would be asked of each
processor developer.</li>

            <li>Guidance concerning interlocking answers to questions is
provided when pertinent.</li>

         </ul>
         <p>Answers to the "testable" questions are expressed as keywords so
that the cataloging information about the test cases will be
readable without reference to this document, at least after one has
attained familiarity with the discretionary areas. The complete set
of keywords, as of this writing, is: <all-choices/>.
         </p>
         <p>Where longer answers are required depending on the brief answer,
the "ELABORATE" flag is shown.</p>
         <p>The questions are not all independent. The "INTERLOCK" flag
appears when answers to two or more questions should be reviewed
for consistency.</p>
    </intro>
    <group-intro status="Implemented">
         <p>The following items represent statements in the XSLT and XPath
Recommendations that identify discretionary behavior that are
controlling test selection in the current version of the test
suite.</p>
    </group-intro>
    <group-intro status="Active">
         <p>The following items represent statements in the XSLT and XPath
Recommendations that identify discretionary behavior that are
proposed for testing in the next deliverable version of the test
suite.</p>
    </group-intro>
    <group-intro status="Postponed">
         <p>The following items represent statements in the XSLT and XPath
Recommendations that identify discretionary behavior that is
proposed to postpone, usually until a "core" test suite is shipped.
Language-concerned items will be added as soon as we have
language-specific tests submitted. Each item should be reviewed and
voted by committee.</p>
    </group-intro>
    <group-intro status="Configuration">
         <p>The following items represent statements in the XSLT and XPath
Recommendations that identify discretionary behaviors that are
acknowledged as discretionary but considered as not testable for
conformance purposes. However, asking the questions is still
reasonable, as it will help test labs configure and use the suite. Any test
marked with any of these discretionary items should be excluded
from the "conformance" suite, but may be useful to distribute. Each
item should be reviewed and voted by the committee.</p>
    </group-intro>
    <group-intro status="Recognized">
         <p>The following items represent statements in the XSLT and XPath
Recommendations that identify discretionary behavior that is out of
scope for XSLT/XPath conformance testing. Items are present here so that the
catalog recognizes all possible discretionary behavior.</p>
         <p>Since the specification explicitly says that the
elements/attributes must not affect the behavior of the XSLT
components, the discretionary alternatives (ignore the foreign
components or take some XSLT-transparent action directed by the
foreign components) do not serve to control exclusion of test
cases.</p>
         <p>The verbiage about setting attribute values specified externally
as default is mainly a warning to stylesheet writers (if you depend
on default values being inserted by validation, your stylesheet may
not work in some scenarios) rather than a grant of discretion to
the developer. More precisely, a developer of a monolithic
parser/styler has discretion to not validate, but that applies to
the parsing phase rather than the transformation phase.</p>
    </group-intro>
    <question-intro>
      <p>Questionnaire for XSLT processor developers</p>
      <p>The XSLT and XPath Recommendations were written in hopes that XML
data could be transformed as needed by the products of many vendors.
Builders of Web sites should be able to use tools to create XSLT
stylesheets regardless of the XSLT processor that will ultimately
execute the styling. The OASIS XSLT/XPath test suite is the most
comprehensive measure of the necessary interoperability.</p>
<p>As a developer trying to meet the W3C Recommendations, you know how
the verbiage of the Recommendations contains precisely-stated
provisions that interlock in complex and sometimes surprising ways.
There are also cases where you have leeway to choose one of two
allowable behaviors or decide output details. Below is our
questionnaire about the choices. We want you to specify the choices
you made when creating your XSLT processor. You are encouraged to
post the answers on your own Web site as well as sending them to us.
When you prepare to use our test suite, an XML document containing
your answers is used to filter out test cases that assume the other
choice, leaving a rendition that is custom-fit to your processor
insofar as allowed by the Recommendations.</p>
<p>Conformance to the Recommendations is tested by running thousands
of small test cases, each with processor inputs and an expected
output. Comparison of actual and expected output neutralizes all
details that have been defined as irrelevant by the XML, InfoSet,
Namespaces, and XSLT Recommendations. There is no reason to think
that all tests have equal weight, hence we discourage talk of
percentages of conformance and the like. If you have some tests
that you would like to be included in a later edition of our
suite, see howtosub.htm for submission instructions.</p>
    </question-intro>
  </verbiage>
  <items>
      <item id="unresolved-strip-preserve-conflict" status="Active">
         <spec-citation spec="XSLT" version="1.0" type="section" place="3.4 Whitespace Stripping"/>
         <spec-citation spec="XSLT" version="1.0" type="XPointer" place="id('strip')/p[7]"/>
         <choices>
            <choice value="choose-last"/>
            <choice value="raise-error"/>
         </choices>
         <excerpt>
            <p>It is an error if this leaves more than one match. <span style="COLOR: red">An XSLT processor may signal the error; if it does not
signal the error, it must recover by choosing, from amongst the
matches that are left, the one that occurs last in the
stylesheet.</span>
            </p>
</excerpt>
            <question scope="Filter">What happens when there is an
unresolved conflict between matches to xsl:strip-space and
xsl:preserve-space elements?</question>
      </item>
      <item id="unresolved-template-rule-conflict" status="Active">
         <spec-citation spec="XSLT" version="1.0" type="section" place="5.5 Conflict Resolution for Template Rules"/>
<spec-citation spec="XSLT" version="1.0" type="XPointer" place="id('conflict')/p[2]"/>
         <choices>
            <choice value="choose-last"/>
            <choice value="raise-error"/>
         </choices>
         <excerpt>
